function [ names, onsets, durations ] = plotOptseq2( filename )
%PLOTOPTSEQ2 plot a *.par file generated by optseq2
%(see https://surfer.nmr.mgh.harvard.edu/optseq/)
%
%   SYNTAXs
%   [ names, onsets, durations ] = plotOptseq2( filename )
%
%   INPUTs
%   filename is a string
%   Without input arguments, an uigetfile will be used to select one
%   graphically.
%
%   NOTES
%   The returned arguments [ names, onsets, durations ] are the cells
%   formated for SPM design in fMRI.
%
%   See also plotSPMnod

% benoit.beranger@icm-institute.org
% CENIR-ICM, 2017


%% Check input arguments

if nargin < 1
    [file,pathname,~] = uigetfile('*.par','Select the *.par optseq2 file');
    if file==0
        fprintf('%s : No file selected \n',mfilename)
        return
    else
        filename = [pathname file];
    end
else
    if ~ischar(filename)
        error('filename must be a char')
    end
end


%% Read & parse file

fid = fopen(filename,'r');

if fid < 0
    error('file cannot be opened : %s',filename)
end

C = textscan(fid, '%f %d %f %d %s');
if isempty(C{1})
    error('file does not seem to be in the expected format : %s',filename)
end

fclose(fid);


%% Create [ names, onsets, durations ]

names = unique(C{5});

for n = 1 : length(names)
    onsets{n} = []; %#ok<*AGROW>
    durations{n} = [];
end

for l = 1 : length(C{1})
    
    i = find(strcmp(names,C{5}{l}));
    onsets{i} = [onsets{i} C{1}(l)];
    durations{i} = [durations{i} C{3}(l)];
    
end


%% Plot

plotSPMnod(names, onsets, durations)


end
